const data = {
  products: [
    {
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt",
      category: "shirt",
      image: "/images/p1.jpg",
      price: 235000,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "Desc of product",
    },
    {
      name: "Adidas Slim Shirt",
      slug: "adidas-slim-shirt",
      category: "shirt",
      image: "/images/p2.jpg",
      price: 235000,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "Desc of product",
    },
    {
      name: "Nike Slim Pant",
      slug: "nike-slim-pants",
      category: "pants",
      image: "/images/p3.jpg",
      price: 235000,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "Desc of product",
    },
    {
      name: "Adidas Fit Pants",
      slug: "adidas-slim-pants",
      category: "shirt",
      image: "/images/p4.jpg",
      price: 235000,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "Desc of product",
    },
  ],
};

export default data;
